#############################################################################
# Makefile for building: bin/finny
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Nov 22 21:16:12 2009
# Project:  finny.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile finny.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -I/usr/include/alsa -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -I/usr/include/alsa -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lhid -lgstinterfaces-0.10 -lgstaudio-0.10 -lgstapp-0.10 -lasound -pthread -lgstreamer-0.10 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -L//lib -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0 -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/mainwindowimpl.cpp \
		src/main.cpp \
		src/AudioInterface.cpp \
		src/radioshark.cpp \
		src/settingsdialog.cpp \
		src/finnysettings.cpp \
		src/mp3settings.cpp \
		src/logging.cpp build/moc_mainwindowimpl.cpp \
		build/moc_settingsdialog.cpp \
		qrc_finny.cpp
OBJECTS       = build/mainwindowimpl.o \
		build/main.o \
		build/AudioInterface.o \
		build/radioshark.o \
		build/settingsdialog.o \
		build/finnysettings.o \
		build/mp3settings.o \
		build/logging.o \
		build/moc_mainwindowimpl.o \
		build/moc_settingsdialog.o \
		build/qrc_finny.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		finny.pro
QMAKE_TARGET  = finny
DESTDIR       = bin/
TARGET        = bin/finny

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_mainwindow.h build/ui_Settings.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: finny.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile finny.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile finny.pro

dist: 
	@$(CHK_DIR_EXISTS) build/finny1.0.0 || $(MKDIR) build/finny1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/finny1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/AudioInterface.h src/radioshark.h src/settingsdialog.h src/finnysettings.h src/mp3settings.h src/logging.h build/finny1.0.0/ && $(COPY_FILE) --parents finny.qrc build/finny1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.cpp src/main.cpp src/AudioInterface.cpp src/radioshark.cpp src/settingsdialog.cpp src/finnysettings.cpp src/mp3settings.cpp src/logging.cpp build/finny1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/Settings.ui build/finny1.0.0/ && (cd `dirname build/finny1.0.0` && $(TAR) finny1.0.0.tar finny1.0.0 && $(COMPRESS) finny1.0.0.tar) && $(MOVE) `dirname build/finny1.0.0`/finny1.0.0.tar.gz . && $(DEL_FILE) -r build/finny1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwindowimpl.cpp build/moc_settingsdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindowimpl.cpp build/moc_settingsdialog.cpp
build/moc_mainwindowimpl.cpp: build/ui_mainwindow.h \
		src/AudioInterface.h \
		src/mp3settings.h \
		src/radioshark.h \
		src/finnysettings.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_settingsdialog.cpp: build/ui_Settings.h \
		src/finnysettings.h \
		src/mp3settings.h \
		src/settingsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/settingsdialog.h -o build/moc_settingsdialog.cpp

compiler_rcc_make_all: qrc_finny.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_finny.cpp
qrc_finny.cpp: finny.qrc \
		assets/vizualization.png \
		assets/finny_icon.png \
		assets/onebit_39.png \
		assets/onebit_12.png \
		assets/sound_on.png \
		assets/fast_right_arrow.png \
		assets/right_arrow.png \
		assets/settings.png \
		assets/record_button.png \
		assets/onebit_34.png \
		assets/onebit_44.png \
		assets/onebit_37.png \
		assets/onebit_33.png \
		assets/recording_tape.png \
		assets/left_arrow.png \
		assets/sound_off.png \
		assets/radioshark.png \
		assets/fast_left_arrow.png
	/usr/bin/rcc -name finny finny.qrc -o qrc_finny.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow.h build/ui_Settings.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow.h build/ui_Settings.h
build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o build/ui_mainwindow.h

build/ui_Settings.h: ui/Settings.ui
	/usr/bin/uic-qt4 ui/Settings.ui -o build/ui_Settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/AudioInterface.h \
		src/mp3settings.h \
		src/radioshark.h \
		src/finnysettings.h \
		src/settingsdialog.h \
		build/ui_Settings.h \
		src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/AudioInterface.h \
		src/mp3settings.h \
		src/radioshark.h \
		src/finnysettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/AudioInterface.o: src/AudioInterface.cpp src/AudioInterface.h \
		src/mp3settings.h \
		src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/AudioInterface.o src/AudioInterface.cpp

build/radioshark.o: src/radioshark.cpp src/radioshark.h \
		src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/radioshark.o src/radioshark.cpp

build/settingsdialog.o: src/settingsdialog.cpp src/settingsdialog.h \
		build/ui_Settings.h \
		src/finnysettings.h \
		src/mp3settings.h \
		src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/settingsdialog.o src/settingsdialog.cpp

build/finnysettings.o: src/finnysettings.cpp src/finnysettings.h \
		src/mp3settings.h \
		src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/finnysettings.o src/finnysettings.cpp

build/mp3settings.o: src/mp3settings.cpp src/mp3settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mp3settings.o src/mp3settings.cpp

build/logging.o: src/logging.cpp src/logging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/logging.o src/logging.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_settingsdialog.o: build/moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_settingsdialog.o build/moc_settingsdialog.cpp

build/qrc_finny.o: qrc_finny.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_finny.o qrc_finny.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

